site_name: Click&Go - קליק אנד גו
site_url: https://amaarets.github.io/AutoKal-2/

theme:
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.path
    - toc.follow
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
  logo: logo.png
  favicon: favicon.ico
  language: he
  name: material
  palette:
    primary: cyan
  font:
    text: Roboto
extra_javascript:
  - javascripts/custom.js
extra_css:
  - stylesheets/custom.css
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg